### ISSUE TITLE
Problem with cert

### ISSUE THREAD

**Issue by SREstudent** [AmanoTeam/Kad#2]
Added kad.crt to trusted store.
When attempt to use `curl --proxy 'http://192.168.xxx.xxx:4000' --url 'https://example.com'`,
result is like this `curl: (51) SSL: certificate subject name 'Kad Root CA' does not match target host name 'example.com'`

What could be wrong?

**Comment by Kartatz** [comment]
Hi,

The README is outdated regarding this specific information. For websites that require an HTTPS connection, you need to disable SSL certificate validation entirely (adding the Kad Root CA to the trust certificate store is not enough).

For curl, it would look like this:

```bash
curl --insecure --proxy 'http://192.168.xxx.xxx:4000' --url 'https://example.com'
```

**Comment by SREstudent** [comment]
Understood.

I think it is possible to generate certificate (with client "trusted" Kad root and the key) for domain, IP served at runtime. And save it on the disk for later reuse. 
Unfortunately my C++ is very rusty to implement it myself.
